development:
  host: localhost
  database: aramiske_development

test:
  host: localhost
  database: aramiske_test

# set these environment variables on your prod server

production:
  host: localhost
  database: aramiske_production

#production:	
#  uri: <%= ENV['MONGOHQ_URL'] %>	
#  host: <%= ENV['MONGOID_HOST'] %>
#  port: <%= ENV['MONGOID_PORT'] %>
#  username: <%= ENV['MONGOID_USERNAME'] %>
#  password: <%= ENV['MONGOID_PASSWORD'] %>
#  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
